# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8df0210f0ad4dab0c08f9f242cf4e258d4781b1ad6dd111cc2774cf4e571aa4f52da00c516ea0672485830885e43b4f11f22ff2675294596ea8ce77fe77d7eb6

test:
  secret_key_base: 96d732c37497e7cc5426a79719e5e2b8951b343187d7c5fbaacb0519fdf241009f695970e547101ac7005ecbdd7a192bb37e62f51bd64ec38f0e1852ca32fbd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
